services:
  drawio:
    image: jgraph/drawio:latest
    container_name: drawio
    restart: always
    ports:
      - 8087:8080
      - 8444:8443
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8087 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
